const{PACKS,validPid,json,site}=require('./_lib');
module.exports=async(req,res)=>{try{if(req.method!=='POST')return json(res,405,{error:'method'});
 const{pid,pack}=req.body||{},p=PACKS[pack];if(!validPid(pid)||!p)return json(res,400,{error:'bad request'});
 const key=process.env.STRIPE_SECRET_KEY;if(!key)return json(res,500,{error:'stripe not configured'});
 const u=site(req),b=new URLSearchParams();
 b.append('mode','payment');b.append('success_url',u+'/?paid=1');b.append('cancel_url',u+'/?paid=0');
 b.append('line_items[0][quantity]','1');b.append('line_items[0][price_data][currency]','eur');
 b.append('line_items[0][price_data][unit_amount]',String(p.cents));b.append('line_items[0][price_data][product_data][name]',p.tokens+' TLTokens (moneda virtual de Team Legend Football)');
 b.append('metadata[pid]',pid.toLowerCase());b.append('metadata[pack]',String(pack));
 b.append('custom_text[submit][message]','Los TLTokens son contenido digital que se entrega de inmediato. Al pagar aceptas perder el derecho de desistimiento una vez entregados. Condiciones: '+u+'/legal.html');
 const r=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/x-www-form-urlencoded'},body:b}),j=await r.json();
 if(!r.ok||!j.url)return json(res,502,{error:'stripe'});json(res,200,{url:j.url})}catch(e){json(res,500,{error:'server'})}};
